export const paths = {
    AUTH: "/auth",
    FORGOTPASSWORD: "/forgot-password",
    RESETPASSWORD: (token = ":token") => `/reset-password/${token}`,
    HOME: "/",
    ABOUT: "/about",
    CONTACT: "/contact",
    FAQ: "/faq",
    SHOP: "/shop",
    NOTFOUND: "/not-found",
    BLOGS: "/blog",
    BLOGDETAIL: (id = ":id") => `/blog/detail/${id}`,
    WISHLIST: "/wishlist",
    LIST: "/list",
    DETAIL: (id = ":id") => `/wine/detail/${id}`,
}