export const paths = {
    AUTH: "/auth",
    FORGOTPASSWORD: "/forgot-password",
    RESETPASSWORD: (token = ":token") => `/reset-password/${token}`,
    HOME: "/",
    ABOUT: "/about",
    CONTACT: "/contact",
    FAQ: "/faq",
    SHOP: "/shop",
    BLOGS: "/blogs",
    BLOGDEATIL: (id = ":id") => `/blog/detail/${id}`,
    WISHLIST: "/wishlist",
    LIST: "/list",
    DETAIL: (id = ":id") => `/detail/${id}`,
}