export const QUERY_KEYS = {
    ADMIN_WINES: "adminWines",
    ADMIN_WINE_DETAIL: "adminWineDetail",
    ADMIN_CATEGORY: "adminCategory",
    ADMIN_BLOG: "adminBlog",
    ADMIN_BLOG_DETAIL: "adminBlogDetail",
    ADMIN_FAQ: "adminFaq",
    USER_CONVERSATION: "userConversation",
    ADMIN_CONVERSATIONS: "adminConversations",
    ADMIN_CHAT: "adminChat",
    ADMIN_ORDERS: "adminOrders",
    ADMIN_REVIEW: "adminReviews",
    CATEGORIES: "categories",
    WINE_LIST: "wineList",
    WINE_DETAIL: "wineDetail",
    BLOG_LIST: "blogList",
    BLOG_DETAIL: "blogDetail",
    FAQ: "faq",
    WISHLIST: "wishList",
    SHOP: "shop",
    ADD_WISHLIST: "addWishlist",
    ORDERS: "orders",
    BASKET: "basket",
    REVIEW: "review"
}